FROM node:alpine as build
# Set working directory
WORKDIR /app
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy the entire project
COPY . .
# Build the application
RUN npm run build
# Serve the built application with Nginx
FROM nginx:alpine
# Copy the built files from the previous stage to the Nginx HTML directory
COPY --from=build /app/dist /usr/share/nginx/html
# Expose port 80
EXPOSE 80
# Command to run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
 
#CHANGE