FROM node:alpine as build
# Set working directory
WORKDIR /app
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy the entire project
COPY . .
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
